os: osx
osx_image: xcode10.3
language: swift
script:
  - xcodebuild clean build -workspace Swiping\ News.xcworkspace -scheme Swiping\ News -destination "platform=iOS Simulator,name=iPhone 7,OS=12.0" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
branches:
 only:
 - master
